controllers/HomeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;


use app\behaviors\NoTokenValidation;
use app\models\Message;
use app\modules\invoice\models\Invoice;
use app\models\User;
use app\helpers\SQL;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class HomeController extends Controller {

    public function behaviors() {
        return [
            'no_csrf' => [
                'class' => NoTokenValidation::class,
                'only' => ['index'],
            ]
        ];
    }

    public function actionIndex() {
        if (static::tryLogin()) {
            Message::show();
        }

        if ('admin' == Yii::$app->layout) {
            return $this->redirect(['/admin/visit']);
        }
        else {
            return $this->render('index', [
                'statistics' => static::statistics()
            ]);
        }
    }

    public static function tryLogin() {
        if (Yii::$app->user->getIsGuest() && isset($_POST['auth'])
            && $user = User::findOne(['auth' => $_POST['auth']])) {
            Yii::$app->user->login($user);
        }
        return !Yii::$app->user->getIsGuest();
    }

    public function actionStatistics() {
        static::tryLogin();
        return $this->render('statistics', ['statistics' => static::statistics()]);
    }

    public function actionError() {
        $exception = Yii::$app->getErrorHandler()->exception;
        $message = $exception->getMessage();
        if ($exception instanceof ForbiddenHttpException) {
            $message = $message ? Yii::t('app', $message) : Yii::t('app', 'Forbidden');
        }
        if ($message) {
            Yii::$app->session->setFlash('error', $message);
        }
        return $this->render('error', [
            'exception' => $exception
        ]);
    }

    public function actionBanner() {
        return $this->render('banner');
    }


    public static function statistics() {
        $started = strtotime(SQL::queryCell('SELECT "time" FROM "journal" WHERE id = 1'));
//        $invested = (int) SQL::queryCell('SELECT count(*) FROM "node"');
        return [
//            'Started' => date('d-m-Y', $started),
            'Running days' => floor((time() - $started)/(3600 * 24)),
            'Users' => User::find()->count(),
            'Total deposited' => Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount > 0')->sum('amount'),
            'Total withdraw' => - Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount < 0')->sum('amount'),
//            'Number of investments' => $invested,
            'Online' => User::online()->count()
        ];
    }

    public function actionTop($by, $top) {
        $top = (int) $top;
        if ($top > 100) {
            return '';
        }
        switch ($by) {
            case 'investors':
                $this->view->title = "Рейтинг вкладчиков (топ-$top)";
                return $this->renderTable('
                  SELECT row_number() over(), user_name, round(sum(price)) as "sum" FROM node
                  JOIN "type" ON type_id = "type".id GROUP BY "user_name" ORDER BY "sum" LIMIT ' . $top,
                    ['Место', 'Игрок', 'Сумма']);
                break;
            case 'rating':
                $this->view->title = "Общий рейтинг(топ-$top)";
                return $this->renderTable('
                  SELECT row_number() over(), user_name, round(sum(amount)) as "sum" FROM invoice
                  WHERE amount > 0 GROUP BY "user_name" ORDER BY "sum" LIMIT ' . $top,
                    ['Место', 'Игрок', 'Сумма']);
                break;
            case 'referrals':
                $this->view->title = "Рейтинг рефераловодов (топ-$top)";
                return $this->renderTable('
                  SELECT row_number() over(), ref_name, count("name") as "count" FROM "user"
                  WHERE ref_name IS NOT NULL GROUP BY "ref_name" ORDER BY "count" DESC LIMIT ' . $top,
                    ['Место', 'Игрок', 'Количество']);
            default:
                return '';
        }
    }

    public function actionCompetition() {
        return $this->render('competition', [
            'prizes' => SQL::queryAll('SELECT * FROM "prize"'),
            'rows' => SQL::queryAll('
                  SELECT t."number", "user_name", "sum", "value" FROM (
                  SELECT row_number() over() as "number", user_name, round(sum(price)) as "sum" FROM node
                  JOIN "type" ON type_id = "type".id
                  GROUP BY "user_name" ORDER BY "sum" LIMIT 5) t
                  JOIN "prize" ON "prize"."number" = t."number"')
        ]);
    }

    protected function renderTable($sql, $headers) {
        return $this->render('table', [
            'rows' => SQL::queryAll($sql),
            'headers' => $headers
        ]);
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\LoginForm;
use app\models\Message;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use app\models\Settings;
use app\modules\bank\models\Node;
use PDO;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'vip' => ['post'],
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'view', 'update', 'cabinet'],
                'manager' => ['complete', 'account'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => Yii::$app->user->identity->isManager() ? null : Yii::$app->user->identity
        ]);
    }

    public function actionView($name = null) {
        if (!$name && Yii::$app->user->isGuest) {
            throw new InvalidParamException();
        }

        $model = $name ? $this->findModel($name) : Yii::$app->user->identity;
        if (Yii::$app->user->isGuest
            || (!Yii::$app->user->identity->isManager() && Yii::$app->user->identity->name != $model->name)) {
            throw new ForbiddenHttpException();
        }

        if ($model->name == Yii::$app->user->identity->name) {
            Message::show();
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCabinet() {
        /** @var User $user */
        $user = Yii::$app->user->identity;
        $command = Yii::$app->db->createCommand('
          SELECT count(*) as count, sum(price * income) as income FROM node JOIN "type" ON type_id = "type".id
          WHERE user_name = :user_name GROUP BY user_name', [':user_name' => $user->name]);
        $command->execute();
        $node = $command->queryOne(PDO::FETCH_OBJ);
        $command = Yii::$app->db->createCommand('
          SELECT sum(price * income / 30) as income FROM node JOIN "type" ON type_id = "type".id
          JOIN income ON node.id = node_id WHERE user_name = :user_name GROUP BY user_name',
            [':user_name' => $user->name]);
        $command->execute();
        $income = $command->queryOne(PDO::FETCH_OBJ);
        return $this->render('cabinet', [
            'model' => $user,
            'firms' => Node::find()->where(['user_name' => $user->name]),
            'hourly' => $node ? $node->income / (30 * 24) : 0,
            'daily' => $node ? $node->income / 30 : 0,
            'profit' => $income ? $income->income : 0,
        ]);
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
            }

            foreach(['forename', 'surname'] as $name) {
                if (empty($model->$name)) {
                    $model->$name = null;
                }
            }

            if ($model->save()) {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup($ref_name = null) {
        $model = new User([
            'scenario' => 'signup'
        ]);
        if (!$ref_name && Yii::$app->session->has('ref_name')) {
            $ref_name = Yii::$app->session->get('ref_name');
        }
        if ($ref_name) {
            $model->ref_name = $ref_name;
            if (!Yii::$app->session->has('ref_name')) {
                Yii::$app->session->set('ref_name', $ref_name);
            }
        }
        if (preg_match('|U\w{7}|', $model->name)) {
            $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
        }
        elseif ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateAuthKey();
            $model->account = Settings::get('account', 'balance');
            $model->status = User::PLAIN;
            if ($model->save(false) && Yii::$app->user->login($model)) {
                return $this->redirect(['/user/cabinet']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new LoginForm(['scenario' => Yii::$app->layout]);
        if ('admin' == $model->getScenario()) {
            $model->duration = 60;
        }

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                            }
                            $user->last_access = date('Y-m-d H:i:s');

                            if ('admin' == Yii::$app->layout && !$user->isManager()) {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'You cannot manage site'));
                            }
                            elseif ($user->save() && Yii::$app->user->login($user,
                                    'admin' == Yii::$app->layout && $model->remember ? $model->duration * 60 : 0)) {
                                return $this->redirect('admin' == Yii::$app->layout ? ['/home/statistics'] : ['/user/cabinet']);
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'
                            ])->orderBy(['time' => SORT_DESC])->one();
                            Yii::$app->session->setFlash('error',
                                Yii::t('app', 'You have exceeded the maximum number of login attempts, you will be able to enter after {time}', [
                                    'time' => $record->time
                                ]));
                        }
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

views/user/_form.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

function submit($label) {
    return Html::submitButton($label, ['class' => 'button']);
}

echo Ext::stamp();

$form = ActiveForm::begin();

if ($model->ref_name && $model->isNewRecord): ?>
    <div class="form-group">
        <?= Yii::t('app', 'Referral') . ': ' . $model->ref_name; ?>
    </div>
    <?= Html::activeHiddenInput($model, 'ref_name') ?>
<?php endif;
if ('signup' == $model->scenario) {
    ?>
    <div id="fullname" class="form-group" style="display: none">
        <label>Ф.И.О</label>
        <input class="form-control" />
    </div>
    <?php
    echo $form->field($model, 'surname');
    echo $form->field($model, 'forename');
    echo $form->field($model, 'patronymic');
    echo $form->field($model, 'email');
    echo $form->field($model, 'perfect');
}

if ($model->isNewRecord) {
    echo $form->field($model, 'name');
}

if ('signup' == $model->scenario):
    echo $form->field($model, 'password')->passwordInput();
    echo $form->field($model, 'repeat')->passwordInput();
    ?>
    <div>
        <div class="always-true">
            <div>Я подтверждаю, что мне 18 лет</div>
            <div class="glyphicon"></div>
        </div>
        <div class="always-true">
            <div>Принять условие пользовательского соглашения</div>
            <div class="glyphicon"></div>
        </div>
    </div>
    <?php
endif;

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'account');
    echo $form->field($model, 'status')->dropDownList(User::statuses());
}

?>
<div style="text-align: center">
    <?php

    if (Yii::$app->user->isGuest) {
        echo submit(Yii::t('app', 'Signup'));
    }
    else {
        echo submit(Yii::t('app', $model->isNewRecord ? 'Create' : 'Update'));
    }

    ActiveForm::end();
    ?>
</div>

views/user/_search.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/account.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\helpers\Html;

?>
<div class="account">
    <h1><?= Yii::t('app', 'Accounts') ?></h1>
    <table class="table">
        <?php
        foreach($model as $key => $value) {
            echo Html::tag('tr',
                Html::tag('td', Yii::t('app', $key)) .
                Html::tag('td', $value)
            );
        }
        ?>
    </table>
</div>

views/user/cabinet.php
<?php
/** @var \app\models\User $model */

use app\models\Settings;
use yii\helpers\Html;

$max_withdraw = Settings::get('account', 'max_withdraw');
?>
<div class="cabinet">
    <h1 class="cabinet-title">
        <span>Кабинет</span>
        <a href="/user/password" class="settings">Настройки</a>
    </h1>
    <div class="profile-stats">
        <div class="red-buttons">
            <?= Html::a('Камень, ножницы, бумага', ['/venture/index'], ['class' => 'btn']) ?>
            <?= Html::a('Мои рефералы', ['/user/index'], ['class' => 'btn']) ?>
            <?= Html::a('История вывода средств', ['/invoice/invoice/index',
                'scenario' => 'withdraw', 'user' => $model->name],
                ['class' => 'btn']) ?>
            <?= Html::a('ТОП-10 инвесторов', ['/home/top', 'by' => 'investors', 'top' => 10],
                ['class' => 'btn']) ?>
            <?= Html::a('ТОП-10 рефераловодов', ['/home/top', 'by' => 'referrals', 'top' => 10],
                ['class' => 'btn']) ?>
            <?= Html::a('ТОП-50 рейтинг', ['/home/top', 'by' => 'rating', 'top' => 50],
                ['class' => 'btn']) ?>
        </div>

        <div align="center" class="orange-buttons">
            <a class="btn" href="/feedback/feedback/create">Служба поддержки</a>
        </div>
        <?php
        if ($model->getVip()):
            echo "<div><strong>VIP-статус</strong>: осталось " . $model->getVipDays() . " дней</div>";
        else:
            ?>
            <div class="vip">
                <div class="left">
                    <div class="title">Ваш статус: <strong>Обычный пользователь</strong></div>
                </div>
                <div class="right">
                    <div class="title">Купите VIP-статус и получите дополнительные преимущества:</div>
                    <ol>
                        <li>Возвращаем <?= Settings::get('account', 'return') * 100 ?>% при покупке предприятия обратно на баланс</li>
                        <li><?= Settings::get('account', 'bonus') * 100 ?>% реферальный бонус (для 1 уровня)</li>
                        <li>Отсутствие ежедневных лимитов на выплаты
                            (без VIP лимит <?= $max_withdraw ?> рублей/день)</li>
                    </ol>
                    <p>
                        Стоимость VIP: <?= Settings::get('account', 'vip') ?> монет. <br>
                        Срок действия: <?= Settings::get('account', 'vip_duration') ?> дней.</p>
                    <div class="orange-buttons">
                        <?= Html::a('Купить', ['/user/vip'], [
                            'class' => 'btn btn-success',
                            'data-method' => 'post'
                        ]) ?>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        <?php endif ?>

        <div class="footer">
            <div class="menu">
                <div class="row1">
                    <p>Баланс: <br><span><?= $model->account ?> монет</span></p>
                    <a class="btn" href="/">Купить бизнес</a>
                    <?= Html::a('Купить монеты', ['/invoice/invoice/create', 'scenario' => 'payment'],
                        ['class' => 'btn']) ?>
                </div>
                <div class="row2">
                    <p>Заработано: <br><span><?= $model->account ?> монет</span></p>
                    <?= Html::a('Вывести', ['/invoice/invoice/create', 'scenario' => 'withdraw'],
                        ['class' => 'btn']) ?>
                </div>
            </div>
            <div class="stats">
                <p>Статистика:</p>
                <div>
                    <table>
                        <tbody>
                        <tr>
                            <td>Бизнесов:</td>
                            <td><?= $firms->count() ?></td>
                        </tr>
                        <tr>
                            <td>Доход(в час):</td>
                            <td><?= floor($hourly * 1000) / 1000 ?> монет</td>
                        </tr>
                        <tr>
                            <td>Доход(в день): </td>
                            <td><?= floor($daily * 1000) / 1000 ?> монет</td>
                        </tr>
                        <tr>
                            <td>Заработано(всего):</td>
                            <td><?= round($profit, 3) ?> монет</td>
                        </tr>
                        <tr>
                            <td>Рефералы(всего):</td>
                            <td>0 руб.</td>
                        </tr>
                        <tr>
                            <td>Денег на вывод:</td>
                            <td><?= $model->account > $max_withdraw ? $max_withdraw : $model->account ?> руб.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="my-business">
            <h2>Мой бизнес</h2>
        </div>

        <div class="business-shop">
            <?= Yii::$app->view->render('@app/modules/bank/views/node/firms', [
                'firms' => $firms->all()
            ]); ?>
        </div>
    </div>
</div>

views/user/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? Yii::t('app', 'Регистрация аккаунта') : Yii::t('app', 'Create User');
?>
<div class="user-create">
    <h1 class="blue-border"><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/user/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', Yii::$app->user->identity->isManager() ? 'Users' : 'Sponsors');

$columns = [
    [
        'attribute' => 'name',
        'format' => 'html',
        'value' => function($model) {
            return Html::a($model->name, ['view', 'name' => $model->name]);
        }
    ],
    'account',
];

if (!Yii::$app->user->getIsGuest() && Yii::$app->user->identity->isAdmin()) {
    $columns[] = 'email:email';
    $columns[] = [
        'format' => 'html',
        'contentOptions' => ['class' => 'action'],
        'value' => function($model) {
            return implode(' ', [
                Html::a('', ['update', 'name' => $model->name], ['class' => 'glyphicon glyphicon-pencil']),
//                Html::a('', ['delete', 'id' => $model->id], ['class' => 'glyphicon glyphicon-trash'])
            ]);
        }
    ];
}
?>
<div class="user-index">
    <div>
        <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?php
            if (Yii::$app->user->identity->isAdmin()) {
                echo Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']);
            }
            ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => $columns,
        ]); ?>
    </div>
</div>

views/user/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/panel.php
<?php
use app\models\Settings;
use yii\helpers\Html;
use yii\helpers\Url;

if (!Yii::$app->user->getIsGuest()):
    ?>
    <div id='user-panel'>
        <ul>
            <li> <?=  Html::a(Yii::t('app', 'Opened Deposits'),
                    ['/bank/node/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <li> <?= Html::a(Yii::t('app', 'Income'),
                    ['/bank/income/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <?php
            if (!Yii::$app->user->isGuest) {
                if ($model->name == Yii::$app->user->identity->name || Yii::$app->user->identity->isAdmin()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Change Password'),
                        ['/user/password', 'name' => $model->name], ['class' => 'btn btn-warning']));
                }
                ?>
                <?php
                if (Yii::$app->user->identity->isManager()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Inform'),
                        ['/message/create', 'user' => $model->name], ['class' => 'btn btn-primary']));
                }
                ?>
                <li> <?= Html::a(Yii::t('app', 'Update'), ['/user/update', 'name' => $model->name], ['class' => 'btn btn-primary']) ?></li>
                <?php

                if ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Sponsors'),
                        ['index'], ['class' => 'btn btn-primary']));
                }

                if (Yii::$app->user->identity->isAdmin()) {
                    if (empty($model->hash)) {
                        echo Html::tag('li', Html::a(Yii::t('app', 'Activate'), ['/user/email', 'code' => $model->name], ['class' => 'btn btn-primary']));
                    }
                    echo Html::tag('li', Html::a(Yii::t('app', 'Delete'), ['/user/delete', 'name' => $model->name
                    ], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                            'method' => 'post',
                        ],
                    ]));
                }
                elseif ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', implode("\n", [
                        Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST'),
                        Html::hiddenInput('PAYEE_ACCOUNT', Settings::get('perfect', 'wallet')),
                        Html::textInput('PAYMENT_AMOUNT', 20, ['size' => 3]),
                        Html::hiddenInput('PAYEE_NAME', Yii::$app->name),
                        Html::hiddenInput('PAYMENT_UNITS', 'USD'),
                        Html::hiddenInput('PAYMENT_URL', Url::to(['/invoice/invoice/success'], true)),
                        Html::hiddenInput('NOPAYMENT_URL', Url::to(['/invoice/invoice/fail'], true)),
                        Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME'),
                        Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name),
                        Html::button(Yii::t('app', 'Pay'), [
                            'name' => 'PAYMENT_METHOD',
                            'type' => 'submit',
                            'class' => 'btn btn-primary'
                        ]),
                        Html::endForm()
                    ]));
                }
            }
            ?>
        </ul>
    </div>
<?php
endif;

views/user/view.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */


$this->title = $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
}

$columns = [
    'name',
    'email:email',
    [
        'attribute' => 'account',
        'format' => 'html',
        'value' => Html::tag('span', $model->account) . ' ' . ($model->account > 0 ? Html::a(Yii::t('app', 'Withdraw'),
                ['invoice/invoice/create', 'amount' => (int) $model->account, 'scenario' => 'withdraw'],
                ['class' => 'btn btn-success btn-xs']) : '')
    ],
    'phone',
    'skype',
    'forename',
    'surname',
    'perfect',
];

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'attribute' => 'status',
        'value' => User::statuses()[$model->status]
    ];
}

$referral = Url::to(['/user/signup', 'ref_name' => $model->name], true);
?>
<div class="roompic"></div>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    require 'panel.php';
    ?>

    <div>
        <div>
            <?php
            echo Html::a(Yii::t('app', 'Referral Link'), $referral, ['class' => 'form-label']);
            ?>

            <input class="form-control" value="<?= Url::to($referral, true); ?>">
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => $columns,
        ]) ?>
    </div>
</div>